# Native builds only - no cross-compilation
# For Linux builds, use Docker containers

# Optimization settings for different targets
[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-cpu=x86-64"]

[target.aarch64-unknown-linux-gnu] 
rustflags = ["-C", "target-cpu=generic"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-cpu=x86-64"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "target-cpu=x86-64"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "target-cpu=apple-m1"]
