[package]
name = "tantivy4java"
version = "1.0.0"
edition = "2021"

[lib]
name = "tantivy4java"
crate-type = ["cdylib"]

[dependencies]
tantivy = "0.22"
jni = { version = "0.21", default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"