// txlog/protocol_regression_tests.rs - Protocol compatibility regression tests
//
// These tests validate that the Rust txlog implementation produces output matching
// the Scala v0.5.4 protocol. They cover:
//   1. Avro binary StateManifest roundtrip (read/write)
//   2. Shared manifest directory structure
//   3. Tombstone accumulation in incremental checkpoints
//   4. FileEntry Avro schema compatibility
//   5. _last_checkpoint JSON format
//   6. Schema deduplication roundtrip
//
// Future: Add tests that read fixtures generated by the actual Scala implementation.

#[cfg(test)]
mod tests {
    use std::collections::{HashMap, HashSet};
    use crate::txlog::actions::*;
    use crate::txlog::avro::{state_writer, state_reader, manifest_writer, manifest_reader, schemas};
    use crate::txlog::schema_dedup;
    use crate::txlog::storage::TxLogStorage;

    fn make_file_entry(path: &str, version: i64, size: i64) -> FileEntry {
        FileEntry {
            add: AddAction {
                path: path.to_string(),
                partition_values: HashMap::new(),
                size,
                modification_time: 1700000000000 + version * 1000,
                data_change: true,
                stats: None,
                min_values: None,
                max_values: None,
                num_records: Some(100),
                footer_start_offset: None,
                footer_end_offset: None,
                has_footer_offsets: None,
                delete_opstamp: None,
                split_tags: None,
                num_merge_ops: None,
                doc_mapping_json: None,
                doc_mapping_ref: None,
                uncompressed_size_bytes: None,
                time_range_start: None,
                time_range_end: None,
                companion_source_files: None,
                companion_delta_version: None,
                companion_fast_field_mode: None,
            },
            added_at_version: version,
            added_at_timestamp: 1700000000000 + version * 1000,
        }
    }

    // ========================================================================
    // 1. StateManifest Avro binary format
    // ========================================================================

    #[test]
    fn test_state_manifest_avro_binary_format() {
        // Verify the StateManifest is written as Avro binary (starts with Obj\x01)
        let manifest = StateManifest {
            version: 10,
            manifests: vec![ManifestInfo {
                path: "manifests/manifest-abc12345.avro".to_string(),
                file_count: 50,
                partition_bounds: None,
                min_added_at_version: 1,
                max_added_at_version: 10,
                tombstone_count: 0,
                live_entry_count: 50,
            }],
            partition_bounds: None,
            created_time: 1700000000000,
            total_file_count: 50,
            format: "avro-state".to_string(),
            protocol_json: None,
            metadata: Some(r#"{"id":"test-table"}"#.to_string()),
            schema_registry: HashMap::new(),
            tombstones: vec![],
            format_version: 1,
            total_bytes: 5000000,
            protocol_version: 4,
        };

        let bytes = state_writer::tests::serialize_for_test(&manifest);

        // Must start with Avro magic bytes
        assert!(bytes.len() >= 4, "Avro output too short");
        assert_eq!(&bytes[0..4], b"Obj\x01", "StateManifest must be Avro binary format");

        // Must roundtrip correctly
        let parsed = state_reader::parse_state_manifest(&bytes).unwrap();
        assert_eq!(parsed.version, 10);
        assert_eq!(parsed.total_file_count, 50);
        assert_eq!(parsed.tombstones.len(), 0);
        assert_eq!(parsed.format_version, 1);
        assert_eq!(parsed.total_bytes, 5000000);
        assert_eq!(parsed.protocol_version, 4);
    }

    #[test]
    fn test_state_manifest_with_tombstones_roundtrip() {
        let manifest = StateManifest {
            version: 25,
            manifests: vec![
                ManifestInfo {
                    path: "manifests/manifest-11111111.avro".to_string(),
                    file_count: 100,
                    partition_bounds: None,
                    min_added_at_version: 1,
                    max_added_at_version: 20,
                    tombstone_count: 3,
                    live_entry_count: 97,
                },
                ManifestInfo {
                    path: "manifests/manifest-22222222.avro".to_string(),
                    file_count: 50,
                    partition_bounds: None,
                    min_added_at_version: 21,
                    max_added_at_version: 25,
                    tombstone_count: 0,
                    live_entry_count: 50,
                },
            ],
            partition_bounds: None,
            created_time: 1700000000000,
            total_file_count: 147,
            format: "avro-state".to_string(),
            protocol_json: None,
            metadata: None,
            schema_registry: HashMap::new(),
            tombstones: vec![
                "splits/removed1.split".to_string(),
                "splits/removed2.split".to_string(),
                "splits/removed3.split".to_string(),
            ],
            format_version: 1,
            total_bytes: 15000000,
            protocol_version: 4,
        };

        let bytes = state_writer::tests::serialize_for_test(&manifest);
        let parsed = state_reader::parse_state_manifest(&bytes).unwrap();

        assert_eq!(parsed.tombstones.len(), 3);
        assert!(parsed.tombstones.contains(&"splits/removed1.split".to_string()));
        assert!(parsed.tombstones.contains(&"splits/removed2.split".to_string()));
        assert!(parsed.tombstones.contains(&"splits/removed3.split".to_string()));
        assert_eq!(parsed.manifests.len(), 2);
        assert_eq!(parsed.manifests[0].tombstone_count, 3);
        assert_eq!(parsed.manifests[1].live_entry_count, 50);
    }

    #[test]
    fn test_state_manifest_with_schema_registry_roundtrip() {
        let mut schema_registry = HashMap::new();
        schema_registry.insert(
            "docMappingSchema.abc123".to_string(),
            r#"{"field_mappings":[{"name":"title","type":"text"}]}"#.to_string(),
        );
        schema_registry.insert(
            "docMappingSchema.def456".to_string(),
            r#"{"field_mappings":[{"name":"body","type":"text"}]}"#.to_string(),
        );

        let manifest = StateManifest {
            version: 5,
            manifests: vec![],
            partition_bounds: None,
            created_time: 1700000000000,
            total_file_count: 0,
            format: "avro-state".to_string(),
            protocol_json: None,
            metadata: None,
            schema_registry: schema_registry.clone(),
            tombstones: vec![],
            format_version: 1,
            total_bytes: 0,
            protocol_version: 4,
        };

        let bytes = state_writer::tests::serialize_for_test(&manifest);
        let parsed = state_reader::parse_state_manifest(&bytes).unwrap();

        assert_eq!(parsed.schema_registry.len(), 2);
        assert_eq!(
            parsed.schema_registry.get("docMappingSchema.abc123"),
            schema_registry.get("docMappingSchema.abc123")
        );
    }

    #[test]
    fn test_state_manifest_with_partition_bounds_roundtrip() {
        let mut min_values = HashMap::new();
        min_values.insert("date".to_string(), "2024-01-01".to_string());
        let mut max_values = HashMap::new();
        max_values.insert("date".to_string(), "2024-12-31".to_string());

        let manifest = StateManifest {
            version: 1,
            manifests: vec![ManifestInfo {
                path: "manifests/manifest-aabbccdd.avro".to_string(),
                file_count: 10,
                partition_bounds: Some(PartitionBounds {
                    min_values: min_values.clone(),
                    max_values: max_values.clone(),
                }),
                min_added_at_version: 1,
                max_added_at_version: 1,
                tombstone_count: 0,
                live_entry_count: 10,
            }],
            partition_bounds: None,
            created_time: 1700000000000,
            total_file_count: 10,
            format: "avro-state".to_string(),
            protocol_json: None,
            metadata: None,
            schema_registry: HashMap::new(),
            tombstones: vec![],
            format_version: 1,
            total_bytes: 100000,
            protocol_version: 4,
        };

        let bytes = state_writer::tests::serialize_for_test(&manifest);
        let parsed = state_reader::parse_state_manifest(&bytes).unwrap();

        let bounds = parsed.manifests[0].partition_bounds.as_ref().unwrap();
        assert_eq!(bounds.min_values.get("date"), Some(&"2024-01-01".to_string()));
        assert_eq!(bounds.max_values.get("date"), Some(&"2024-12-31".to_string()));
    }

    // ========================================================================
    // 2. FileEntry Avro schema compatibility
    // ========================================================================

    #[test]
    fn test_file_entry_schema_matches_scala() {
        let schema = schemas::file_entry_schema();
        match &schema {
            apache_avro::Schema::Record(r) => {
                assert_eq!(r.name.fullname(None), "io.indextables.state.FileEntry");

                // Verify key Scala fields are present
                let field_names: Vec<&str> = r.fields.iter()
                    .map(|f| f.name.as_str())
                    .collect();

                // Required Scala fields
                assert!(field_names.contains(&"path"));
                assert!(field_names.contains(&"partitionValues"));
                assert!(field_names.contains(&"size"));
                assert!(field_names.contains(&"modificationTime"));
                assert!(field_names.contains(&"dataChange"));
                assert!(field_names.contains(&"hasFooterOffsets"));
                assert!(field_names.contains(&"splitTags"));
                assert!(field_names.contains(&"numMergeOps"));
                assert!(field_names.contains(&"docMappingRef"));
                assert!(field_names.contains(&"uncompressedSizeBytes"));
                assert!(field_names.contains(&"addedAtVersion"));
                assert!(field_names.contains(&"addedAtTimestamp"));
                assert!(field_names.contains(&"companionSourceFiles"));

                // Extension fields kept for roundtrip compat
                // (Scala ignores unknown fields via schema evolution)
                assert!(field_names.contains(&"deleteOpstamp"));
                assert!(field_names.contains(&"docMappingJson"));
                assert!(field_names.contains(&"timeRangeStart"));
                assert!(field_names.contains(&"timeRangeEnd"));
            }
            _ => panic!("Expected Record schema"),
        }
    }

    #[test]
    fn test_file_entry_avro_roundtrip() {
        let entries = vec![
            make_file_entry("splits/file1.split", 1, 10000),
            make_file_entry("splits/file2.split", 2, 20000),
        ];

        let bytes = manifest_writer::write_manifest_bytes(&entries).unwrap();

        // Must be Avro binary
        assert_eq!(&bytes[0..4], b"Obj\x01");

        let parsed = manifest_reader::read_manifest_bytes(&bytes).unwrap();
        assert_eq!(parsed.len(), 2);
        assert_eq!(parsed[0].add.path, "splits/file1.split");
        assert_eq!(parsed[0].add.size, 10000);
        assert_eq!(parsed[0].added_at_version, 1);
        assert_eq!(parsed[1].add.path, "splits/file2.split");
        assert_eq!(parsed[1].added_at_version, 2);
    }

    #[test]
    fn test_file_entry_with_all_optional_fields() {
        let mut entry = make_file_entry("splits/full.split", 5, 50000);
        entry.add.stats = Some(r#"{"numRecords":100}"#.to_string());
        entry.add.min_values = Some({
            let mut m = HashMap::new();
            m.insert("id".to_string(), "1".to_string());
            m
        });
        entry.add.max_values = Some({
            let mut m = HashMap::new();
            m.insert("id".to_string(), "999".to_string());
            m
        });
        entry.add.num_records = Some(100);
        entry.add.footer_start_offset = Some(45000);
        entry.add.footer_end_offset = Some(50000);
        entry.add.has_footer_offsets = Some(true);
        entry.add.split_tags = Some(vec!["tag1".to_string(), "tag2".to_string()]);
        entry.add.num_merge_ops = Some(3);
        entry.add.doc_mapping_ref = Some("abc123hash".to_string());
        entry.add.uncompressed_size_bytes = Some(75000);
        entry.add.companion_source_files = Some(vec!["data/file1.parquet".to_string()]);
        entry.add.companion_delta_version = Some(42);
        entry.add.companion_fast_field_mode = Some("HYBRID".to_string());

        let bytes = manifest_writer::write_manifest_bytes(&[entry]).unwrap();
        let parsed = manifest_reader::read_manifest_bytes(&bytes).unwrap();

        assert_eq!(parsed.len(), 1);
        let p = &parsed[0];
        assert_eq!(p.add.stats.as_deref(), Some(r#"{"numRecords":100}"#));
        assert_eq!(p.add.footer_start_offset, Some(45000));
        assert_eq!(p.add.has_footer_offsets, Some(true));
        assert_eq!(p.add.split_tags.as_ref().unwrap().len(), 2);
        assert_eq!(p.add.num_merge_ops, Some(3));
        assert_eq!(p.add.doc_mapping_ref.as_deref(), Some("abc123hash"));
        assert_eq!(p.add.companion_fast_field_mode.as_deref(), Some("HYBRID"));
    }

    // ========================================================================
    // 3. _last_checkpoint JSON format
    // ========================================================================

    #[test]
    fn test_last_checkpoint_json_format() {
        let info = LastCheckpointInfo {
            version: 42,
            size: 1000,
            size_in_bytes: 50000,
            num_files: 1000,
            created_time: 1700000000000,
            format: Some("avro-state".to_string()),
            state_dir: Some("state-v00000000000000000042".to_string()),
            parts: None,
            checkpoint_id: None,
        };

        let json = serde_json::to_string(&info).unwrap();
        let parsed: serde_json::Value = serde_json::from_str(&json).unwrap();

        // Verify all required fields are present (matching Scala)
        assert_eq!(parsed["version"], 42);
        assert_eq!(parsed["size"], 1000);
        assert_eq!(parsed["sizeInBytes"], 50000);
        assert_eq!(parsed["numFiles"], 1000);
        assert_eq!(parsed["createdTime"], 1700000000000i64);
        assert_eq!(parsed["format"], "avro-state");
        assert_eq!(parsed["stateDir"], "state-v00000000000000000042");

        // Optional fields should not be present when None
        assert!(parsed.get("parts").is_none() || parsed["parts"].is_null());
        assert!(parsed.get("checkpointId").is_none() || parsed["checkpointId"].is_null());
    }

    #[test]
    fn test_last_checkpoint_roundtrip() {
        let info = LastCheckpointInfo {
            version: 100,
            size: 5000,
            size_in_bytes: 250000,
            num_files: 5000,
            created_time: 1700000000000,
            format: Some("avro-state".to_string()),
            state_dir: Some("state-v00000000000000000100".to_string()),
            parts: None,
            checkpoint_id: None,
        };

        let json = serde_json::to_vec(&info).unwrap();
        let parsed: LastCheckpointInfo = serde_json::from_slice(&json).unwrap();

        assert_eq!(parsed.version, 100);
        assert_eq!(parsed.size_in_bytes, 250000);
        assert_eq!(parsed.num_files, 5000);
        assert_eq!(parsed.created_time, 1700000000000);
        assert_eq!(parsed.format, Some("avro-state".to_string()));
    }

    // ========================================================================
    // 4. State directory naming
    // ========================================================================

    #[test]
    fn test_state_dir_naming_matches_scala() {
        // Scala uses f"state-v$version%020d"
        assert_eq!(TxLogStorage::state_dir_name(0), "state-v00000000000000000000");
        assert_eq!(TxLogStorage::state_dir_name(1), "state-v00000000000000000001");
        assert_eq!(TxLogStorage::state_dir_name(100), "state-v00000000000000000100");
        assert_eq!(TxLogStorage::state_dir_name(310), "state-v00000000000000000310");
        assert_eq!(TxLogStorage::state_dir_name(99999999999999999), "state-v00099999999999999999");
    }

    // ========================================================================
    // 5. Manifest path resolution
    // ========================================================================

    #[test]
    fn test_manifest_path_resolution_shared() {
        // Scala shared format: manifests/manifest-{id}.avro (relative to txlog root)
        let path = state_reader::resolve_manifest_path(
            "state-v00000000000000000042",
            "manifests/manifest-abc12345.avro",
        );
        assert_eq!(path, "manifests/manifest-abc12345.avro",
            "Shared manifest path should NOT be prefixed with state dir");
    }

    #[test]
    fn test_manifest_path_resolution_per_state() {
        // Legacy per-state format: manifest-NNNN.avro (relative to state dir)
        let path = state_reader::resolve_manifest_path(
            "state-v00000000000000000042",
            "manifest-0000.avro",
        );
        assert_eq!(path, "state-v00000000000000000042/manifest-0000.avro",
            "Per-state manifest path should be prefixed with state dir");
    }

    #[test]
    fn test_manifest_path_resolution_normalized_legacy() {
        // Normalized legacy: state-vN/manifest-{id}.avro (already has directory)
        let path = state_reader::resolve_manifest_path(
            "state-v00000000000000000099",
            "state-v00000000000000000042/manifest-abc12345.avro",
        );
        assert_eq!(path, "state-v00000000000000000042/manifest-abc12345.avro",
            "Normalized legacy path should not be double-prefixed");
    }

    // ========================================================================
    // 6. Schema deduplication compatibility
    // ========================================================================

    #[test]
    fn test_schema_dedup_hash_length() {
        // Scala produces 16-char URL-safe Base64 hashes
        let schema = r#"{"field_mappings":[{"name":"title","type":"text"}]}"#;
        let mut actions = vec![crate::txlog::actions::Action::Add(AddAction {
            path: "test.split".to_string(),
            partition_values: HashMap::new(),
            size: 100,
            modification_time: 0,
            data_change: true,
            stats: None, min_values: None, max_values: None, num_records: None,
            footer_start_offset: None, footer_end_offset: None, has_footer_offsets: None,
            delete_opstamp: None,
            split_tags: None, num_merge_ops: None,
            doc_mapping_json: Some(schema.to_string()),
            doc_mapping_ref: None,
            uncompressed_size_bytes: None,
            time_range_start: None, time_range_end: None,
            companion_source_files: None, companion_delta_version: None,
            companion_fast_field_mode: None,
        })];

        let new_schemas = schema_dedup::deduplicate_schemas(&mut actions, &HashMap::new());
        assert_eq!(new_schemas.len(), 1);

        // Verify hash is 16 chars
        for (key, _) in &new_schemas {
            let hash = key.strip_prefix("docMappingSchema.").unwrap();
            assert_eq!(hash.len(), 16, "Schema hash must be 16 chars (matching Scala)");
        }

        // Verify the add action now has ref, not json
        if let Action::Add(a) = &actions[0] {
            assert!(a.doc_mapping_json.is_none());
            assert!(a.doc_mapping_ref.is_some());
            assert_eq!(a.doc_mapping_ref.as_ref().unwrap().len(), 16);
        }
    }

    #[test]
    fn test_schema_dedup_deterministic_across_key_order() {
        // Scala sorts keys before hashing — verify our hashes match regardless of key order
        let schema1 = r#"{"a":1,"b":2}"#;
        let schema2 = r#"{"b":2,"a":1}"#;

        let mut actions1 = vec![Action::Add(AddAction {
            path: "t1.split".to_string(),
            partition_values: HashMap::new(),
            size: 100, modification_time: 0, data_change: true,
            stats: None, min_values: None, max_values: None, num_records: None,
            footer_start_offset: None, footer_end_offset: None, has_footer_offsets: None,
            delete_opstamp: None, split_tags: None, num_merge_ops: None,
            doc_mapping_json: Some(schema1.to_string()),
            doc_mapping_ref: None, uncompressed_size_bytes: None,
            time_range_start: None, time_range_end: None,
            companion_source_files: None, companion_delta_version: None,
            companion_fast_field_mode: None,
        })];
        let mut actions2 = vec![Action::Add(AddAction {
            path: "t2.split".to_string(),
            partition_values: HashMap::new(),
            size: 100, modification_time: 0, data_change: true,
            stats: None, min_values: None, max_values: None, num_records: None,
            footer_start_offset: None, footer_end_offset: None, has_footer_offsets: None,
            delete_opstamp: None, split_tags: None, num_merge_ops: None,
            doc_mapping_json: Some(schema2.to_string()),
            doc_mapping_ref: None, uncompressed_size_bytes: None,
            time_range_start: None, time_range_end: None,
            companion_source_files: None, companion_delta_version: None,
            companion_fast_field_mode: None,
        })];

        let schemas1 = schema_dedup::deduplicate_schemas(&mut actions1, &HashMap::new());
        let schemas2 = schema_dedup::deduplicate_schemas(&mut actions2, &HashMap::new());

        // Same schema with different key order should produce same hash
        let hash1: Vec<&String> = schemas1.keys().collect();
        let hash2: Vec<&String> = schemas2.keys().collect();
        assert_eq!(hash1, hash2, "Schema hashes must be deterministic regardless of key order");
    }

    // ========================================================================
    // 7. Tombstone filtering on read
    // ========================================================================

    #[test]
    fn test_tombstone_filtering_in_file_entry_read() {
        // Create entries
        let entries = vec![
            make_file_entry("splits/live1.split", 1, 1000),
            make_file_entry("splits/dead.split", 1, 1000),
            make_file_entry("splits/live2.split", 2, 2000),
        ];

        // Write to manifest
        let manifest_bytes = manifest_writer::write_manifest_bytes(&entries).unwrap();

        // Simulate reading with tombstones
        let mut read_entries = manifest_reader::read_manifest_bytes(&manifest_bytes).unwrap();
        assert_eq!(read_entries.len(), 3);

        // Apply tombstone filtering (as read_all_manifests does)
        let tombstones: HashSet<&str> = ["splits/dead.split"].into_iter().collect();
        read_entries.retain(|e| !tombstones.contains(e.add.path.as_str()));
        assert_eq!(read_entries.len(), 2);
        assert_eq!(read_entries[0].add.path, "splits/live1.split");
        assert_eq!(read_entries[1].add.path, "splits/live2.split");
    }

    // ========================================================================
    // 8. StateManifest schema field ordering matches Scala
    // ========================================================================

    #[test]
    fn test_state_manifest_schema_field_order() {
        let schema = schemas::state_manifest_schema();
        match &schema {
            apache_avro::Schema::Record(r) => {
                let field_names: Vec<&str> = r.fields.iter()
                    .map(|f| f.name.as_str())
                    .collect();

                // Scala schema field order (must match exactly for Avro binary compat)
                assert_eq!(field_names, vec![
                    "formatVersion",
                    "stateVersion",
                    "createdAt",
                    "numFiles",
                    "totalBytes",
                    "manifests",
                    "tombstones",
                    "schemaRegistry",
                    "protocolVersion",
                    "metadata",
                ]);
            }
            _ => panic!("Expected Record schema"),
        }
    }

    // ========================================================================
    // 9. Manifest ID generation
    // ========================================================================

    #[test]
    fn test_manifest_id_format() {
        // Generate 16-char hex from UUID for sufficient entropy
        for _ in 0..10 {
            let id = state_writer::tests::generate_manifest_id_for_test();
            assert_eq!(id.len(), 16, "Manifest ID must be 16 chars");
            assert!(id.chars().all(|c| c.is_ascii_hexdigit()),
                "Manifest ID must be hex: {}", id);
        }
    }

    #[test]
    fn test_manifest_ids_are_unique() {
        let ids: HashSet<String> = (0..100)
            .map(|_| state_writer::tests::generate_manifest_id_for_test())
            .collect();
        assert_eq!(ids.len(), 100, "Manifest IDs must be unique");
    }

    // ========================================================================
    // 10. Version file path format
    // ========================================================================

    #[test]
    fn test_version_path_format() {
        assert_eq!(TxLogStorage::version_path(0), "00000000000000000000.json");
        assert_eq!(TxLogStorage::version_path(1), "00000000000000000001.json");
        assert_eq!(TxLogStorage::version_path(42), "00000000000000000042.json");
    }

    // ========================================================================
    // 11. Protocol version in StateManifest
    // ========================================================================

    #[test]
    fn test_protocol_version_persisted() {
        let manifest = StateManifest {
            version: 1,
            manifests: vec![],
            partition_bounds: None,
            created_time: 1700000000000,
            total_file_count: 0,
            format: "avro-state".to_string(),
            protocol_json: None,
            metadata: None,
            schema_registry: HashMap::new(),
            tombstones: vec![],
            format_version: 1,
            total_bytes: 0,
            protocol_version: 4,
        };

        let bytes = state_writer::tests::serialize_for_test(&manifest);
        let parsed = state_reader::parse_state_manifest(&bytes).unwrap();
        assert_eq!(parsed.protocol_version, 4);

        // protocol_json should be reconstructed from protocol_version
        let protocol_json = parsed.protocol_json.as_ref().unwrap();
        let protocol: ProtocolAction = serde_json::from_str(protocol_json).unwrap();
        assert_eq!(protocol.min_reader_version, 4);
        assert_eq!(protocol.min_writer_version, 4);
    }

    // ========================================================================
    // Scala-generated fixture reading tests
    //
    // These read actual transaction logs generated by Scala v0.5.4 and validate
    // that the Rust reader can parse every component correctly.
    // ========================================================================

    const FIXTURE_BASE: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/src/txlog/test_fixtures/indextables_spark_v0.5.4");

    fn fixture_path(name: &str) -> String {
        format!("{}/{}", FIXTURE_BASE, name)
    }

    fn read_fixture_last_checkpoint(name: &str) -> Option<LastCheckpointInfo> {
        let path = format!("{}/_transaction_log/_last_checkpoint", fixture_path(name));
        let data = std::fs::read(&path).ok()?;
        serde_json::from_slice(&data).ok()
    }

    fn read_fixture_state_manifest(name: &str, state_dir: &str) -> StateManifest {
        let path = format!("{}/_transaction_log/{}/{}", fixture_path(name), state_dir, STATE_MANIFEST_FILENAME);
        let data = std::fs::read(&path).expect(&format!("Failed to read {}", path));
        state_reader::parse_state_manifest(&data).expect(&format!("Failed to parse {}", path))
    }

    fn read_fixture_manifest_avro(name: &str, manifest_path: &str) -> Vec<FileEntry> {
        let full_path = format!("{}/_transaction_log/{}", fixture_path(name), manifest_path);
        let data = std::fs::read(&full_path).expect(&format!("Failed to read {}", full_path));
        manifest_reader::read_manifest_bytes(&data).expect(&format!("Failed to parse {}", full_path))
    }

    fn fixture_exists(name: &str) -> bool {
        std::path::Path::new(&fixture_path(name)).exists()
    }

    // --- 01: Simple single write ---

    #[test]
    fn test_scala_fixture_01_single_write_checkpoint() {
        if !fixture_exists("01_single_write") { return; }
        let cp = read_fixture_last_checkpoint("01_single_write").expect("should have checkpoint");
        assert!(cp.version >= 1);
        assert!(cp.num_files >= 1);
        assert_eq!(cp.format, Some("avro-state".to_string()));
        assert!(cp.state_dir.is_some());
    }

    #[test]
    fn test_scala_fixture_01_single_write_state_manifest() {
        if !fixture_exists("01_single_write") { return; }
        let cp = read_fixture_last_checkpoint("01_single_write").unwrap();
        let state_dir = cp.state_dir.unwrap();
        let manifest = read_fixture_state_manifest("01_single_write", &state_dir);

        assert_eq!(manifest.format_version, 1);
        assert_eq!(manifest.protocol_version, 4);
        assert!(manifest.total_file_count >= 1);
        assert!(!manifest.manifests.is_empty(), "should have at least 1 manifest");
        assert!(manifest.tombstones.is_empty(), "single write should have no tombstones");
    }

    #[test]
    fn test_scala_fixture_01_single_write_file_entries() {
        if !fixture_exists("01_single_write") { return; }
        let cp = read_fixture_last_checkpoint("01_single_write").unwrap();
        let state_dir = cp.state_dir.unwrap();
        let manifest = read_fixture_state_manifest("01_single_write", &state_dir);

        let mut total_entries = 0;
        for mi in &manifest.manifests {
            let resolved = state_reader::resolve_manifest_path(&state_dir, &mi.path);
            let entries = read_fixture_manifest_avro("01_single_write", &resolved);
            assert!(!entries.is_empty());
            for entry in &entries {
                assert!(!entry.add.path.is_empty());
                assert!(entry.add.size > 0);
                assert!(entry.added_at_version >= 0);
            }
            total_entries += entries.len();
        }
        assert_eq!(total_entries as i64, manifest.total_file_count);
    }

    // --- 03: With removes/tombstones ---

    #[test]
    fn test_scala_fixture_03_with_removes() {
        if !fixture_exists("03_with_removes") { return; }
        let cp = read_fixture_last_checkpoint("03_with_removes").unwrap();
        let state_dir = cp.state_dir.unwrap();
        let manifest = read_fixture_state_manifest("03_with_removes", &state_dir);

        // After overwrite, there should be remove actions in the txlog
        // The latest checkpoint may or may not have tombstones depending on
        // whether it was a compacted or incremental write
        assert!(manifest.total_file_count >= 1, "should have at least 1 live file after overwrite");
    }

    // --- 04: Partitioned ---

    #[test]
    fn test_scala_fixture_04_partitioned() {
        if !fixture_exists("04_partitioned") { return; }
        let cp = read_fixture_last_checkpoint("04_partitioned").unwrap();
        let state_dir = cp.state_dir.unwrap();
        let manifest = read_fixture_state_manifest("04_partitioned", &state_dir);

        // Read entries and verify partition values
        let mut has_partition_values = false;
        for mi in &manifest.manifests {
            let resolved = state_reader::resolve_manifest_path(&state_dir, &mi.path);
            let entries = read_fixture_manifest_avro("04_partitioned", &resolved);
            for entry in &entries {
                if !entry.add.partition_values.is_empty() {
                    has_partition_values = true;
                    assert!(entry.add.partition_values.contains_key("date"),
                        "partitioned fixture should have 'date' partition: {:?}", entry.add.partition_values);
                }
            }
        }
        assert!(has_partition_values, "partitioned fixture should have entries with partition values");
    }

    // --- 05: Many transactions ---

    #[test]
    fn test_scala_fixture_05_many_transactions() {
        if !fixture_exists("05_many_transactions") { return; }
        let cp = read_fixture_last_checkpoint("05_many_transactions").unwrap();
        let state_dir = cp.state_dir.unwrap();
        let manifest = read_fixture_state_manifest("05_many_transactions", &state_dir);

        // 15 writes * 3 rows each = 45 files total
        assert!(manifest.total_file_count >= 15, "many transactions should have many files, got {}", manifest.total_file_count);
        // Should reference shared manifests
        for mi in &manifest.manifests {
            assert!(mi.path.starts_with("manifests/") || mi.path.contains("/"),
                "manifest path should be shared: {}", mi.path);
        }
    }

    // --- 06: Schema dedup ---

    #[test]
    fn test_scala_fixture_06_schema_dedup() {
        if !fixture_exists("06_schema_dedup") { return; }
        let cp = read_fixture_last_checkpoint("06_schema_dedup").unwrap();
        let state_dir = cp.state_dir.unwrap();
        let manifest = read_fixture_state_manifest("06_schema_dedup", &state_dir);

        // Should have schema registry entries
        assert!(!manifest.schema_registry.is_empty(),
            "schema dedup fixture should have schema registry entries");

        // Schema registry keys are the raw hash values (16-char Base64)
        for key in manifest.schema_registry.keys() {
            // Keys may be raw hashes or prefixed with docMappingSchema.
            assert!(key.len() >= 16 || key.starts_with("docMappingSchema."),
                "schema registry key should be a hash or prefixed: {}", key);
        }

        // Read entries and verify docMappingRef is populated
        let mut has_ref = false;
        for mi in &manifest.manifests {
            let resolved = state_reader::resolve_manifest_path(&state_dir, &mi.path);
            let entries = read_fixture_manifest_avro("06_schema_dedup", &resolved);
            for entry in &entries {
                if entry.add.doc_mapping_ref.is_some() {
                    has_ref = true;
                    let ref_key = entry.add.doc_mapping_ref.as_ref().unwrap();
                    assert_eq!(ref_key.len(), 16, "docMappingRef should be 16-char hash");
                    // Verify ref exists in registry (may be prefixed or raw)
                    let prefixed_key = format!("docMappingSchema.{}", ref_key);
                    let in_registry = manifest.schema_registry.contains_key(&prefixed_key)
                        || manifest.schema_registry.contains_key(ref_key);
                    assert!(in_registry,
                        "docMappingRef {} should exist in schema registry", ref_key);
                }
            }
        }
        assert!(has_ref, "schema dedup fixture should have entries with docMappingRef");
    }

    // --- 12: Partition drop ---

    #[test]
    fn test_scala_fixture_12_partition_drop() {
        if !fixture_exists("12_partition_drop") { return; }
        let cp = read_fixture_last_checkpoint("12_partition_drop").unwrap();
        let state_dir = cp.state_dir.unwrap();
        let manifest = read_fixture_state_manifest("12_partition_drop", &state_dir);

        // After dropping date=2024-01-02, should have tombstones or fewer files
        // Read all entries and apply tombstones
        let mut all_entries = Vec::new();
        for mi in &manifest.manifests {
            let resolved = state_reader::resolve_manifest_path(&state_dir, &mi.path);
            let entries = read_fixture_manifest_avro("12_partition_drop", &resolved);
            all_entries.extend(entries);
        }

        // Apply tombstones
        if !manifest.tombstones.is_empty() {
            let tombstone_set: HashSet<&str> = manifest.tombstones.iter().map(|s| s.as_str()).collect();
            all_entries.retain(|e| !tombstone_set.contains(e.add.path.as_str()));
        }

        // Should have fewer live files than original 6 (dropped date=2024-01-02)
        assert!(all_entries.len() < 6 && all_entries.len() >= 1,
            "after partition drop, should have fewer than 6 live files, got {}", all_entries.len());

        // None of the remaining should be from the dropped partition
        for entry in &all_entries {
            let date = entry.add.partition_values.get("date");
            assert_ne!(date, Some(&"2024-01-02".to_string()),
                "dropped partition date=2024-01-02 should not appear in live entries");
        }
    }

    // --- 13: After purge ---

    #[test]
    fn test_scala_fixture_13_after_purge() {
        if !fixture_exists("13_after_purge") { return; }
        let cp = read_fixture_last_checkpoint("13_after_purge").unwrap();
        let state_dir = cp.state_dir.unwrap();
        let manifest = read_fixture_state_manifest("13_after_purge", &state_dir);

        // After purge, the state manifest should still be readable and valid
        assert!(manifest.total_file_count >= 1, "should still have files after purge");
        assert_eq!(manifest.protocol_version, 4);
    }

    // --- 14: After merge ---

    #[test]
    fn test_scala_fixture_14_after_merge() {
        if !fixture_exists("14_after_merge") { return; }
        let cp = read_fixture_last_checkpoint("14_after_merge").unwrap();
        let state_dir = cp.state_dir.unwrap();
        let manifest = read_fixture_state_manifest("14_after_merge", &state_dir);

        // After merge, should have fewer files (merged) and the txlog should be readable
        assert!(manifest.total_file_count >= 1);
        // Merged files may have numMergeOps > 0
        let mut total_entries = 0;
        for mi in &manifest.manifests {
            let resolved = state_reader::resolve_manifest_path(&state_dir, &mi.path);
            let entries = read_fixture_manifest_avro("14_after_merge", &resolved);
            total_entries += entries.len();
        }
        assert!(total_entries >= 1);
    }

    // ========================================================================
    // Additional helpers for comprehensive fixture tests
    // ========================================================================

    /// Read a version file from a fixture (parse_version_file handles decompression internally)
    fn read_fixture_version_file(name: &str, version: i64) -> Vec<Action> {
        let version_path = format!("{}/_transaction_log/{}",
            fixture_path(name),
            TxLogStorage::version_path(version));
        let data = std::fs::read(&version_path)
            .expect(&format!("Failed to read {}", version_path));
        crate::txlog::version_file::parse_version_file(&data)
            .expect("parse failed")
    }

    /// Get all live entries from a fixture (state manifest + tombstone filtering)
    fn get_live_entries(name: &str) -> (StateManifest, Vec<FileEntry>) {
        let cp = read_fixture_last_checkpoint(name).unwrap();
        let state_dir = cp.state_dir.unwrap();
        let manifest = read_fixture_state_manifest(name, &state_dir);
        let mut all_entries = Vec::new();
        for mi in &manifest.manifests {
            let resolved = state_reader::resolve_manifest_path(&state_dir, &mi.path);
            let entries = read_fixture_manifest_avro(name, &resolved);
            all_entries.extend(entries);
        }
        // Apply tombstones
        if !manifest.tombstones.is_empty() {
            let tombstone_set: HashSet<&str> = manifest.tombstones.iter()
                .map(|s| s.as_str()).collect();
            all_entries.retain(|e| !tombstone_set.contains(e.add.path.as_str()));
        }
        (manifest, all_entries)
    }

    // ========================================================================
    // Fixture 02: Five appends — shared manifest reuse
    // ========================================================================

    #[test]
    fn test_scala_fixture_02_shared_manifest_reuse() {
        if !fixture_exists("02_five_appends") { return; }
        let cp = read_fixture_last_checkpoint("02_five_appends").unwrap();
        let state_dir = cp.state_dir.unwrap();
        let manifest = read_fixture_state_manifest("02_five_appends", &state_dir);

        // Should reference multiple shared manifests
        assert!(manifest.manifests.len() >= 2,
            "five appends should produce multiple shared manifests, got {}",
            manifest.manifests.len());

        // All manifest paths should start with manifests/
        for mi in &manifest.manifests {
            assert!(mi.path.starts_with("manifests/"),
                "shared manifest path should start with manifests/: {}", mi.path);
        }

        // Verify version tracking - manifests should have valid version ranges
        for mi in &manifest.manifests {
            assert!(mi.max_added_at_version >= mi.min_added_at_version,
                "max_added_at_version ({}) should be >= min ({})",
                mi.max_added_at_version, mi.min_added_at_version);
        }

        // Verify total entry count matches sum of manifest file_count values
        let sum_file_count: i64 = manifest.manifests.iter()
            .map(|mi| mi.file_count).sum();
        assert_eq!(manifest.total_file_count, sum_file_count,
            "total_file_count ({}) should match sum of manifest file_counts ({})",
            manifest.total_file_count, sum_file_count);

        // Read all entries, verify there are entries from five appends
        let (_, entries) = get_live_entries("02_five_appends");
        assert_eq!(entries.len() as i64, manifest.total_file_count,
            "entry count should match total_file_count");
        assert!(entries.len() >= 5,
            "five appends should produce at least 5 entries, got {}", entries.len());
    }

    // ========================================================================
    // Fixture 07: Two writes — version-only read path
    // ========================================================================

    #[test]
    fn test_scala_fixture_07_two_writes_checkpoint_and_state() {
        if !fixture_exists("07_two_writes_no_checkpoint") { return; }
        let cp = read_fixture_last_checkpoint("07_two_writes_no_checkpoint").unwrap();
        let state_dir = cp.state_dir.unwrap();
        let manifest = read_fixture_state_manifest("07_two_writes_no_checkpoint", &state_dir);

        assert!(manifest.version >= 1,
            "state manifest version should be >= 1, got {}", manifest.version);
        assert!(manifest.total_file_count >= 1,
            "should have at least 1 file, got {}", manifest.total_file_count);
    }

    #[test]
    fn test_scala_fixture_07_version_0_contains_protocol_and_metadata() {
        if !fixture_exists("07_two_writes_no_checkpoint") { return; }
        let actions = read_fixture_version_file("07_two_writes_no_checkpoint", 0);

        let has_protocol = actions.iter().any(|a| matches!(a, Action::Protocol(_)));
        let has_metadata = actions.iter().any(|a| matches!(a, Action::MetaData(_)));

        assert!(has_protocol, "version 0 should contain ProtocolAction");
        assert!(has_metadata, "version 0 should contain MetadataAction");
    }

    // ========================================================================
    // Fixture 08: Ten writes at checkpoint boundary
    // ========================================================================

    #[test]
    fn test_scala_fixture_08_checkpoint_at_version_10() {
        if !fixture_exists("08_ten_writes_at_checkpoint") { return; }
        let cp = read_fixture_last_checkpoint("08_ten_writes_at_checkpoint").unwrap();
        assert!(cp.version >= 10,
            "checkpoint should be at version >= 10, got {}", cp.version);

        let state_dir = cp.state_dir.unwrap();
        let manifest = read_fixture_state_manifest("08_ten_writes_at_checkpoint", &state_dir);

        // Should have multiple shared manifests (one per write or batched)
        assert!(manifest.manifests.len() >= 1,
            "should have at least 1 manifest, got {}", manifest.manifests.len());

        // Verify total_file_count = 20 (10 writes * 2 rows each)
        assert_eq!(manifest.total_file_count, 20,
            "10 writes * 2 rows each = 20 total files, got {}", manifest.total_file_count);

        // Check manifest file_count values are valid
        for mi in &manifest.manifests {
            assert!(mi.file_count >= 1,
                "each manifest should have file_count >= 1, got {}", mi.file_count);
        }
    }

    // ========================================================================
    // Fixture 09: Partitioned multi-append
    // ========================================================================

    #[test]
    fn test_scala_fixture_09_partition_values_present() {
        if !fixture_exists("09_partitioned_multi_append") { return; }
        let (manifest, entries) = get_live_entries("09_partitioned_multi_append");

        // All entries should have partition values
        for entry in &entries {
            assert!(!entry.add.partition_values.is_empty(),
                "partitioned entries should have partition values: path={}",
                entry.add.path);
        }

        // Verify manifest partition bounds exist and have correct date column
        let mut has_partition_bounds = false;
        for mi in &manifest.manifests {
            if let Some(ref bounds) = mi.partition_bounds {
                has_partition_bounds = true;
                assert!(bounds.min_values.contains_key("date"),
                    "partition bounds should have min for 'date' column");
                assert!(bounds.max_values.contains_key("date"),
                    "partition bounds should have max for 'date' column");
            }
        }
        assert!(has_partition_bounds,
            "partitioned multi-append should have at least one manifest with partition bounds");
    }

    #[test]
    fn test_scala_fixture_09_streaming_version_filter() {
        if !fixture_exists("09_partitioned_multi_append") { return; }
        let cp = read_fixture_last_checkpoint("09_partitioned_multi_append").unwrap();
        let state_dir = cp.state_dir.unwrap();
        let manifest = read_fixture_state_manifest("09_partitioned_multi_append", &state_dir);

        use crate::txlog::streaming;

        // Filter with since_version=0 should return all manifests
        let all = streaming::filter_manifests_by_version(&manifest.manifests, 0);
        assert_eq!(all.len(), manifest.manifests.len(),
            "since_version=0 should return all manifests");

        // Filter with a high version should return fewer or no manifests
        let high_version = manifest.version + 100;
        let none = streaming::filter_manifests_by_version(&manifest.manifests, high_version);
        assert!(none.is_empty() || none.iter().all(|m| m.max_added_at_version == 0),
            "since_version beyond latest should return no manifests (or only unknown-version ones)");

        // Filter for version=1 should return at least the manifest containing v1 entries
        let v1 = streaming::filter_manifests_for_version(&manifest.manifests, 1);
        assert!(!v1.is_empty(),
            "filter_manifests_for_version(1) should find at least one manifest");
    }

    // ========================================================================
    // Fixture 10: Large batch
    // ========================================================================

    #[test]
    fn test_scala_fixture_10_large_batch_entries() {
        if !fixture_exists("10_large_batch") { return; }
        let cp = read_fixture_last_checkpoint("10_large_batch").unwrap();
        let (manifest, entries) = get_live_entries("10_large_batch");

        // Verify entry count matches checkpoint num_files
        assert_eq!(entries.len() as i64, cp.num_files,
            "large batch entry count should match checkpoint num_files ({}), got {}",
            cp.num_files, entries.len());
        assert_eq!(entries.len() as i64, manifest.total_file_count,
            "large batch entry count should match total_file_count");

        // Verify num_records is populated on all entries
        for entry in &entries {
            assert!(entry.add.num_records.is_some(),
                "num_records should be populated on entry: {}", entry.add.path);
        }

        // Verify size > 0 on all entries
        for entry in &entries {
            assert!(entry.add.size > 0,
                "size should be > 0 on entry: {}", entry.add.path);
        }
    }

    // ========================================================================
    // Fixture 11: Mixed operations (append, overwrite, append)
    // ========================================================================

    #[test]
    fn test_scala_fixture_11_mixed_operations_final_state() {
        if !fixture_exists("11_mixed_operations") { return; }
        let (manifest, entries) = get_live_entries("11_mixed_operations");

        // After overwrite + append, latest state should have only files from
        // the overwrite and subsequent append
        assert!(entries.len() >= 1,
            "should have at least 1 live file after mixed operations");

        // Verify the live count equals total_file_count (tombstones already applied)
        assert_eq!(entries.len() as i64, manifest.total_file_count,
            "live entries ({}) should match total_file_count ({})",
            entries.len(), manifest.total_file_count);
    }

    // ========================================================================
    // Fixture 15: Drop then purge
    // ========================================================================

    #[test]
    fn test_scala_fixture_15_drop_then_purge_valid_state() {
        if !fixture_exists("15_drop_then_purge") { return; }
        let cp = read_fixture_last_checkpoint("15_drop_then_purge").unwrap();
        let state_dir = cp.state_dir.unwrap();
        let manifest = read_fixture_state_manifest("15_drop_then_purge", &state_dir);

        // State should be valid after purge
        assert_eq!(manifest.format_version, 1);
        assert_eq!(manifest.protocol_version, 4);

        // Verify metadata field is parseable as JSON (if present)
        if let Some(ref metadata_json) = manifest.metadata {
            let parsed: serde_json::Value = serde_json::from_str(metadata_json)
                .expect("metadata field should be parseable JSON");
            assert!(parsed.is_object(),
                "metadata should be a JSON object");
        }
    }

    #[test]
    fn test_scala_fixture_15_old_state_dirs_after_purge() {
        if !fixture_exists("15_drop_then_purge") { return; }
        let cp = read_fixture_last_checkpoint("15_drop_then_purge").unwrap();

        // After purge, some old state directories may have been removed
        // Verify that the current state dir exists
        let state_dir = cp.state_dir.as_ref().unwrap();
        let current_state_path = format!("{}/_transaction_log/{}",
            fixture_path("15_drop_then_purge"), state_dir);
        assert!(std::path::Path::new(&current_state_path).exists(),
            "current state dir should exist after purge: {}", current_state_path);

        // Check that version 0 state dir may have been cleaned up
        let v0_state = format!("{}/_transaction_log/state-v00000000000000000000",
            fixture_path("15_drop_then_purge"));
        // v0 might or might not exist after purge - just log it
        let _v0_exists = std::path::Path::new(&v0_state).exists();
    }

    // ========================================================================
    // Fixture 16: With skip actions
    // ========================================================================

    #[test]
    fn test_scala_fixture_16_skip_actions_readable() {
        if !fixture_exists("16_with_skip_actions") { return; }

        // Read the fixture state and verify it has valid structure
        let cp = read_fixture_last_checkpoint("16_with_skip_actions").unwrap();
        let state_dir = cp.state_dir.unwrap();
        let manifest = read_fixture_state_manifest("16_with_skip_actions", &state_dir);

        assert!(manifest.total_file_count >= 1,
            "skip actions fixture should have entries");
        assert_eq!(manifest.protocol_version, 4);

        // Scan version files for MergeSkip actions if they exist
        let mut found_skip = false;
        for version in 0..20 {
            let version_path = format!("{}/_transaction_log/{}",
                fixture_path("16_with_skip_actions"),
                TxLogStorage::version_path(version));
            if !std::path::Path::new(&version_path).exists() {
                continue;
            }
            let actions = read_fixture_version_file("16_with_skip_actions", version);
            for action in &actions {
                if let Action::MergeSkip(skip) = action {
                    found_skip = true;
                    assert!(!skip.path.is_empty(),
                        "skip action should have a path");
                    assert!(skip.skip_timestamp > 0,
                        "skip action should have a positive timestamp");
                }
            }
        }
        // Skip actions may only appear in version files that were not checkpointed,
        // or they may be encoded differently in the Scala implementation.
        // If found, verify them; otherwise just confirm the fixture is readable.
        if !found_skip {
            // Verify entries are readable even without explicit skip actions in version files
            let (_, entries) = get_live_entries("16_with_skip_actions");
            assert!(!entries.is_empty(),
                "skip actions fixture should have live entries");
        }
    }

    #[test]
    fn test_scala_fixture_16_entries_num_merge_ops() {
        if !fixture_exists("16_with_skip_actions") { return; }
        let (_, entries) = get_live_entries("16_with_skip_actions");

        // Check if any entries have num_merge_ops populated
        let has_merge_ops = entries.iter()
            .any(|e| e.add.num_merge_ops.is_some());

        // If merge ran, some entries should have num_merge_ops
        // This is optional - just verify they parse if present
        for entry in &entries {
            if let Some(ops) = entry.add.num_merge_ops {
                assert!(ops >= 0,
                    "num_merge_ops should be >= 0, got {} for {}", ops, entry.add.path);
            }
        }

        // Log whether merge ops were found (informational)
        if !has_merge_ops {
            // Not an error - skip actions don't require merge ops on entries
        }
    }

    // ========================================================================
    // Protocol aspect tests — version file parsing
    // ========================================================================

    #[test]
    fn test_version_0_protocol_and_metadata_from_fixture_02() {
        if !fixture_exists("02_five_appends") { return; }
        let actions = read_fixture_version_file("02_five_appends", 0);

        // First action should be ProtocolAction with minReaderVersion=4
        let protocol = actions.iter().find_map(|a| match a {
            Action::Protocol(p) => Some(p),
            _ => None,
        }).expect("version 0 should contain ProtocolAction");
        assert_eq!(protocol.min_reader_version, 4,
            "protocol minReaderVersion should be 4, got {}", protocol.min_reader_version);

        // Second should be MetadataAction with schemaString, partitionColumns, format
        let metadata = actions.iter().find_map(|a| match a {
            Action::MetaData(m) => Some(m),
            _ => None,
        }).expect("version 0 should contain MetadataAction");
        assert!(!metadata.schema_string.is_empty(),
            "MetadataAction should have non-empty schemaString");
        // partitionColumns may be empty for non-partitioned fixtures
        assert!(!metadata.format.provider.is_empty(),
            "MetadataAction.format.provider should be populated");
    }

    // ========================================================================
    // Protocol aspect tests — schema registry restore
    // ========================================================================

    #[test]
    fn test_schema_registry_restore_from_fixture_06() {
        if !fixture_exists("06_schema_dedup") { return; }
        let (manifest, entries) = get_live_entries("06_schema_dedup");

        // Find entries with docMappingRef
        let entries_with_ref: Vec<&FileEntry> = entries.iter()
            .filter(|e| e.add.doc_mapping_ref.is_some())
            .collect();
        assert!(!entries_with_ref.is_empty(),
            "schema_dedup fixture should have entries with docMappingRef");

        // Look up each ref in schema_registry and verify it resolves
        for entry in &entries_with_ref {
            let ref_key = entry.add.doc_mapping_ref.as_ref().unwrap();
            let prefixed_key = format!("docMappingSchema.{}", ref_key);
            let schema_value = manifest.schema_registry.get(&prefixed_key)
                .or_else(|| manifest.schema_registry.get(ref_key))
                .expect(&format!("docMappingRef {} should exist in schema_registry", ref_key));

            // Verify the registry value is non-empty
            assert!(!schema_value.is_empty(),
                "schema registry value should be non-empty for ref {}", ref_key);
        }
    }

    // ========================================================================
    // Protocol aspect tests — manifest version ranges for streaming
    // ========================================================================

    #[test]
    fn test_manifest_version_ranges_streaming_from_fixture_05() {
        if !fixture_exists("05_many_transactions") { return; }
        let cp = read_fixture_last_checkpoint("05_many_transactions").unwrap();
        let state_dir = cp.state_dir.unwrap();
        let manifest = read_fixture_state_manifest("05_many_transactions", &state_dir);

        use crate::txlog::streaming;

        // filter_manifests_by_version should correctly filter
        let since_3 = streaming::filter_manifests_by_version(&manifest.manifests, 3);
        // Should only include manifests with max_added_at_version > 3
        for mi in &since_3 {
            assert!(mi.max_added_at_version > 3 || mi.max_added_at_version == 0,
                "filtered manifest should have max_added_at_version > 3, got {}",
                mi.max_added_at_version);
        }

        // filter_manifests_for_version with a specific version
        let for_v5 = streaming::filter_manifests_for_version(&manifest.manifests, 5);
        for mi in &for_v5 {
            assert!(
                (mi.min_added_at_version <= 5 && mi.max_added_at_version >= 5)
                    || (mi.min_added_at_version == 0 && mi.max_added_at_version == 0),
                "manifest for version 5 should span that version: [{}, {}]",
                mi.min_added_at_version, mi.max_added_at_version);
        }

        // Since version > latest should return empty (or only unknown-version)
        let beyond = streaming::filter_manifests_by_version(&manifest.manifests, manifest.version + 1);
        assert!(beyond.is_empty() || beyond.iter().all(|m| m.max_added_at_version == 0),
            "filtering beyond latest version should return empty");
    }

    // ========================================================================
    // Protocol aspect tests — tombstone count accuracy
    // ========================================================================

    #[test]
    fn test_tombstone_count_accuracy_fixture_12() {
        if !fixture_exists("12_partition_drop") { return; }
        let cp = read_fixture_last_checkpoint("12_partition_drop").unwrap();
        let state_dir = cp.state_dir.unwrap();
        let manifest = read_fixture_state_manifest("12_partition_drop", &state_dir);

        // Total tombstone_count across manifests should be consistent with tombstones list
        let total_tombstone_count: i64 = manifest.manifests.iter()
            .map(|m| m.tombstone_count).sum();

        // The tombstones list in the state manifest tracks removed paths
        // tombstone_count in manifests indicates how many entries in each manifest are dead
        // These may not be exactly equal but both should be >= 0
        assert!(total_tombstone_count >= 0,
            "total tombstone_count should be >= 0, got {}", total_tombstone_count);

        if !manifest.tombstones.is_empty() {
            assert_eq!(manifest.tombstones.len() as i64, total_tombstone_count,
                "tombstones list length ({}) should match total tombstone_count ({})",
                manifest.tombstones.len(), total_tombstone_count);
        }
    }

    #[test]
    fn test_tombstone_count_accuracy_fixture_03() {
        if !fixture_exists("03_with_removes") { return; }
        let cp = read_fixture_last_checkpoint("03_with_removes").unwrap();
        let state_dir = cp.state_dir.unwrap();
        let manifest = read_fixture_state_manifest("03_with_removes", &state_dir);

        // After removes, tombstones or reduced file count should reflect removals
        let total_tombstone_count: i64 = manifest.manifests.iter()
            .map(|m| m.tombstone_count).sum();

        // Either tombstones list or tombstone_count should indicate removed files
        let has_removals = !manifest.tombstones.is_empty() || total_tombstone_count > 0
            || manifest.total_file_count < 4; // original 2 writes * 2 rows = 4, overwrite reduces
        assert!(has_removals,
            "with_removes fixture should show evidence of removals: tombstones={}, tombstone_count={}, total_files={}",
            manifest.tombstones.len(), total_tombstone_count, manifest.total_file_count);
    }

    // ========================================================================
    // Protocol aspect tests — StateManifest metadata field
    // ========================================================================

    #[test]
    fn test_state_manifest_metadata_field_parsing() {
        // Test across multiple fixtures that have metadata
        let fixtures = [
            "01_single_write", "02_five_appends", "04_partitioned",
            "05_many_transactions", "08_ten_writes_at_checkpoint",
        ];

        for fixture_name in &fixtures {
            if !fixture_exists(fixture_name) { continue; }
            let cp = match read_fixture_last_checkpoint(fixture_name) {
                Some(cp) => cp,
                None => continue,
            };
            let state_dir = match cp.state_dir {
                Some(d) => d,
                None => continue,
            };
            let manifest = read_fixture_state_manifest(fixture_name, &state_dir);

            if let Some(ref metadata_json) = manifest.metadata {
                let parsed: serde_json::Value = serde_json::from_str(metadata_json)
                    .expect(&format!("metadata should be valid JSON in {}: {}",
                        fixture_name, metadata_json));
                assert!(parsed.is_object(),
                    "{}: metadata should be a JSON object", fixture_name);
            }
        }
    }

    #[test]
    fn test_state_manifest_metadata_partition_columns_fixture_04() {
        if !fixture_exists("04_partitioned") { return; }
        let cp = read_fixture_last_checkpoint("04_partitioned").unwrap();
        let state_dir = cp.state_dir.unwrap();
        let manifest = read_fixture_state_manifest("04_partitioned", &state_dir);

        // Check metadata in state manifest OR in version 0 MetadataAction
        if let Some(ref metadata_json) = manifest.metadata {
            let parsed: serde_json::Value = serde_json::from_str(metadata_json)
                .expect("metadata should be valid JSON");
            if let Some(partition_cols) = parsed.get("partitionColumns") {
                let cols: Vec<String> = serde_json::from_value(partition_cols.clone())
                    .expect("partitionColumns should be array of strings");
                assert!(cols.contains(&"date".to_string()),
                    "partitionColumns should contain 'date', got {:?}", cols);
                return;
            }
        }

        // Fall back to checking version 0 MetadataAction
        let actions = read_fixture_version_file("04_partitioned", 0);
        let metadata = actions.iter().find_map(|a| match a {
            Action::MetaData(m) => Some(m),
            _ => None,
        }).expect("version 0 should have MetadataAction");
        assert!(metadata.partition_columns.contains(&"date".to_string()),
            "MetadataAction partitionColumns should contain 'date', got {:?}",
            metadata.partition_columns);
    }

    // ========================================================================
    // Wrapped metadata format (Scala compatibility)
    // ========================================================================

    /// `parse_metadata_json` must handle both the bare format written by Rust
    /// and the `{"metaData": {...}}` envelope written by Scala's CheckpointCommand.
    #[test]
    fn test_parse_metadata_json_bare_format() {
        let bare = r#"{"id":"abc","schemaString":"{}","partitionColumns":[],"configuration":{},"createdTime":0,"format":{"provider":"delta","options":{}}}"#;
        let m = crate::txlog::distributed::parse_metadata_json(bare);
        assert!(m.is_some(), "bare format should parse successfully");
        assert_eq!(m.unwrap().id, "abc");
    }

    #[test]
    fn test_parse_metadata_json_scala_wrapped_format() {
        let inner = r#"{"id":"72200663-test","schemaString":"{}","partitionColumns":["message_date"],"configuration":{},"createdTime":1234,"format":{"provider":"delta","options":{}}}"#;
        let wrapped = format!(r#"{{"metaData": {}}}"#, inner);
        let m = crate::txlog::distributed::parse_metadata_json(&wrapped);
        assert!(m.is_some(), "Scala-wrapped {{\"metaData\": ...}} format should parse successfully");
        let m = m.unwrap();
        assert_eq!(m.id, "72200663-test");
        assert_eq!(m.partition_columns, vec!["message_date"]);
    }

    #[test]
    fn test_parse_metadata_json_invalid_returns_none() {
        assert!(crate::txlog::distributed::parse_metadata_json("not json").is_none());
        assert!(crate::txlog::distributed::parse_metadata_json(r#"{"other":"key"}"#).is_none());
        assert!(crate::txlog::distributed::parse_metadata_json(r#"{"metaData": null}"#).is_none());
    }

    /// Round-trip: writer emits wrapped format; reader unwraps it back to MetadataAction.
    #[test]
    fn test_writer_emits_wrapped_metadata_reader_can_parse() {
        use crate::txlog::actions::MetadataAction;
        let original = MetadataAction {
            id: "roundtrip-id".to_string(),
            name: None,
            description: None,
            schema_string: r#"{"type":"struct","fields":[]}"#.to_string(),
            partition_columns: vec!["date".to_string()],
            configuration: std::collections::HashMap::new(),
            created_time: Some(9999),
            format: Default::default(),
        };
        // Simulate writer: wrap in {"metaData": {...}}
        let written = serde_json::to_value(&original).unwrap();
        let on_disk = serde_json::json!({"metaData": written}).to_string();
        // Simulate reader: parse_metadata_json should unwrap correctly
        let parsed = crate::txlog::distributed::parse_metadata_json(&on_disk)
            .expect("parse_metadata_json should succeed on writer output");
        assert_eq!(parsed.id, original.id);
        assert_eq!(parsed.partition_columns, original.partition_columns);
    }

    // ========================================================================
    // Protocol aspect tests — footer offsets scan
    // ========================================================================

    #[test]
    fn test_footer_offsets_scan_across_fixtures() {
        let fixtures = [
            "01_single_write", "02_five_appends", "04_partitioned",
            "05_many_transactions", "10_large_batch", "14_after_merge",
        ];

        let mut found_footer_offsets = false;
        for fixture_name in &fixtures {
            if !fixture_exists(fixture_name) { continue; }
            let (_, entries) = get_live_entries(fixture_name);
            for entry in &entries {
                if entry.add.footer_start_offset.is_some()
                    || entry.add.footer_end_offset.is_some()
                {
                    found_footer_offsets = true;
                    // If footer offsets are present, hasFooterOffsets should be true
                    if let Some(has) = entry.add.has_footer_offsets {
                        assert!(has,
                            "has_footer_offsets should be true when footer offsets are populated: {}",
                            entry.add.path);
                    }
                    // Start should be < end
                    if let (Some(start), Some(end)) = (entry.add.footer_start_offset, entry.add.footer_end_offset) {
                        assert!(start < end,
                            "footer_start_offset ({}) should be < footer_end_offset ({}): {}",
                            start, end, entry.add.path);
                    }
                }
            }
        }
        // Footer offsets may not be present in basic fixtures - not an error
        if !found_footer_offsets {
            // Informational: no footer offsets found across scanned fixtures
        }
    }

    // ========================================================================
    // Protocol aspect tests — companion fields scan
    // ========================================================================

    #[test]
    fn test_companion_fields_scan_across_fixtures() {
        let fixtures = [
            "01_single_write", "02_five_appends", "04_partitioned",
            "05_many_transactions", "10_large_batch", "14_after_merge",
        ];

        for fixture_name in &fixtures {
            if !fixture_exists(fixture_name) { continue; }
            let (_, entries) = get_live_entries(fixture_name);
            for entry in &entries {
                // Regular table fixtures likely won't have companion fields
                // Just verify they parse as None/empty
                if let Some(ref sources) = entry.add.companion_source_files {
                    // If present, should be non-empty
                    assert!(!sources.is_empty(),
                        "companion_source_files should be non-empty if present: {}",
                        entry.add.path);
                }
                if let Some(delta_ver) = entry.add.companion_delta_version {
                    assert!(delta_ver >= 0,
                        "companion_delta_version should be >= 0: {}", entry.add.path);
                }
                // companion_fast_field_mode: if present, should be a known mode
                if let Some(ref mode) = entry.add.companion_fast_field_mode {
                    let known_modes = ["NONE", "HYBRID", "NATIVE", "PARQUET"];
                    assert!(known_modes.contains(&mode.as_str()),
                        "companion_fast_field_mode should be a known mode, got '{}': {}",
                        mode, entry.add.path);
                }
            }
        }
    }

    // ========================================================================
    // Comprehensive fixture existence and readability test
    // ========================================================================

    #[test]
    fn test_all_16_fixtures_readable() {
        let fixtures = [
            "01_single_write", "02_five_appends", "03_with_removes",
            "04_partitioned", "05_many_transactions", "06_schema_dedup",
            "07_two_writes_no_checkpoint", "08_ten_writes_at_checkpoint",
            "09_partitioned_multi_append", "10_large_batch",
            "11_mixed_operations", "12_partition_drop",
            "13_after_purge", "14_after_merge",
            "15_drop_then_purge", "16_with_skip_actions",
        ];

        let mut readable_count = 0;
        for fixture_name in &fixtures {
            if !fixture_exists(fixture_name) {
                continue;
            }
            readable_count += 1;

            // Every fixture should have a valid checkpoint
            let cp = read_fixture_last_checkpoint(fixture_name)
                .expect(&format!("{}: should have _last_checkpoint", fixture_name));
            assert!(cp.version >= 0,
                "{}: checkpoint version should be >= 0", fixture_name);
            assert_eq!(cp.format, Some("avro-state".to_string()),
                "{}: checkpoint format should be avro-state", fixture_name);

            // Every fixture should have a readable state manifest
            let state_dir = cp.state_dir
                .expect(&format!("{}: checkpoint should have stateDir", fixture_name));
            let manifest = read_fixture_state_manifest(fixture_name, &state_dir);
            assert_eq!(manifest.format_version, 1,
                "{}: format_version should be 1", fixture_name);
            assert_eq!(manifest.protocol_version, 4,
                "{}: protocol_version should be 4", fixture_name);

            // Every fixture should have version 0 with protocol + metadata
            let v0_path = format!("{}/_transaction_log/{}",
                fixture_path(fixture_name),
                TxLogStorage::version_path(0));
            if std::path::Path::new(&v0_path).exists() {
                let actions = read_fixture_version_file(fixture_name, 0);
                assert!(actions.iter().any(|a| matches!(a, Action::Protocol(_))),
                    "{}: version 0 should have ProtocolAction", fixture_name);
                assert!(actions.iter().any(|a| matches!(a, Action::MetaData(_))),
                    "{}: version 0 should have MetadataAction", fixture_name);
            }
        }

        assert_eq!(readable_count, 16,
            "all 16 fixtures should exist and be readable, only found {}", readable_count);
    }

    // ========================================================================
    // All manifest entries readable across all fixtures
    // ========================================================================

    #[test]
    fn test_all_fixture_manifest_entries_readable() {
        let fixtures = [
            "01_single_write", "02_five_appends", "03_with_removes",
            "04_partitioned", "05_many_transactions", "06_schema_dedup",
            "07_two_writes_no_checkpoint", "08_ten_writes_at_checkpoint",
            "09_partitioned_multi_append", "10_large_batch",
            "11_mixed_operations", "12_partition_drop",
            "13_after_purge", "14_after_merge",
            "15_drop_then_purge", "16_with_skip_actions",
        ];

        for fixture_name in &fixtures {
            if !fixture_exists(fixture_name) { continue; }
            let cp = read_fixture_last_checkpoint(fixture_name).unwrap();
            let state_dir = cp.state_dir.unwrap();
            let manifest = read_fixture_state_manifest(fixture_name, &state_dir);

            let mut total_read = 0;
            for mi in &manifest.manifests {
                let resolved = state_reader::resolve_manifest_path(&state_dir, &mi.path);
                let entries = read_fixture_manifest_avro(fixture_name, &resolved);
                assert_eq!(entries.len() as i64, mi.file_count,
                    "{}: manifest {} file_count ({}) should match entries read ({})",
                    fixture_name, mi.path, mi.file_count, entries.len());

                for entry in &entries {
                    assert!(!entry.add.path.is_empty(),
                        "{}: entry should have non-empty path", fixture_name);
                    assert!(entry.add.size >= 0,
                        "{}: entry size should be non-negative", fixture_name);
                    assert!(entry.added_at_version >= 0,
                        "{}: added_at_version should be >= 0", fixture_name);
                }
                total_read += entries.len();
            }

            // After applying tombstones, live count should match
            let tombstone_set: HashSet<&str> = manifest.tombstones.iter()
                .map(|s| s.as_str()).collect();
            let live_count = if tombstone_set.is_empty() {
                total_read
            } else {
                // Re-read and filter
                let mut live = 0;
                for mi in &manifest.manifests {
                    let resolved = state_reader::resolve_manifest_path(&state_dir, &mi.path);
                    let entries = read_fixture_manifest_avro(fixture_name, &resolved);
                    live += entries.iter()
                        .filter(|e| !tombstone_set.contains(e.add.path.as_str()))
                        .count();
                }
                live
            };

            assert_eq!(live_count as i64, manifest.total_file_count,
                "{}: live entry count ({}) should match total_file_count ({})",
                fixture_name, live_count, manifest.total_file_count);
        }
    }

    // --- 17: Truncated log (post-TRUNCATE TIME TRAVEL) ---

    #[test]
    fn test_scala_fixture_17_truncated_log_self_contained() {
        if !fixture_exists("17_truncated_log") { return; }
        let cp = read_fixture_last_checkpoint("17_truncated_log").unwrap();
        let state_dir = cp.state_dir.unwrap();
        let manifest = read_fixture_state_manifest("17_truncated_log", &state_dir);

        // After truncation, the checkpoint must be self-contained:
        // - protocol_version should be populated
        // - metadata field should contain the MetadataAction JSON (if present)
        assert_eq!(manifest.protocol_version, 4);

        // If metadata is cached, verify it's valid JSON
        if let Some(ref metadata_json) = manifest.metadata {
            let metadata: serde_json::Value = serde_json::from_str(metadata_json)
                .expect("cached metadata should be valid JSON");
            // MetadataAction has id and schemaString fields
            assert!(metadata.is_object(), "metadata should be a JSON object");
        }

        // Should still be able to read all file entries
        let mut total_entries = 0;
        for mi in &manifest.manifests {
            let resolved = state_reader::resolve_manifest_path(&state_dir, &mi.path);
            let entries = read_fixture_manifest_avro("17_truncated_log", &resolved);
            total_entries += entries.len();
        }
        assert!(total_entries >= 1, "should have readable entries even after truncation");
    }
}
